import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { DatabaseSync } from 'node:sqlite';

test('event deletion enforces permissions and removes only the selected event and its attachments', async t => {
  const data=mkdtempSync(join(tmpdir(),'little-dreams-delete-'));
  const server=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,DATA_DIR:data,PORT:'0',HOST:'127.0.0.1',BACKUP_ENABLED:'0'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{const stopped=once(server,'exit');server.kill();await stopped;rmSync(data,{recursive:true,force:true});});
  let logs='';
  server.stderr.on('data',chunk=>{logs+=chunk;});
  const ready=await Promise.race([once(server.stdout,'data'),once(server,'exit').then(()=>{throw new Error(logs);})]);
  const port=/port (\d+)/.exec(String(ready[0]))?.[1];
  assert.ok(port && port!=='0','server reports its bound port');
  const base=`http://127.0.0.1:${port}`;
  async function request(path,body,cookie='') {
    const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{origin:base,'content-type':'application/json',cookie},body:body===undefined?undefined:JSON.stringify(body)});
    return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
  }
  const profile={albumName:'Test',childName:'Child',birthDate:'2026-01-01',sex:'unspecified'};
  const parent=await request('/api/register',{...profile,name:'Parent',email:'parent@example.test',password:'test-password-123'});
  assert.equal(parent.status,200);
  const cookie=parent.cookie,album=(await request('/api/me',undefined,cookie)).body.albums[0].id;
  const second=(await request('/api/albums',profile,cookie)).body.id;
  const create=async(title,extra={})=>request('/api/moments',{album,title,date:'2026-02-01',description:'',files:[{name:'test.pdf',type:'application/pdf',data:Buffer.from('%PDF-1.4 test').toString('base64')}],...extra},cookie);
  const target=(await create('Delete me',{milestoneKey:'smile'})).body.id;
  const retained=(await create('Keep me')).body.id;
  const invitation=(await request('/api/invites',{album,role:'viewer'},cookie)).body.token;
  const viewer=await request('/api/register',{name:'Viewer',email:'viewer@example.test',password:'test-password-123',invite:invitation});
  assert.equal(viewer.status,200);
  assert.equal((await request('/api/comments',{moment:target,body:'A comment'},viewer.cookie)).status,201);
  const moments=(await request('/api/moments?album='+album,undefined,cookie)).body;
  const file=moments.find(m=>m.id===target).files[0].id;
  const payload={album,id:target};
  assert.equal((await request('/api/moments/delete',payload)).status,401);
  assert.equal((await request('/api/moments/delete',payload,viewer.cookie)).status,403);
  assert.equal((await request('/api/moments/delete',{album:second,id:target},cookie)).status,404);
  assert.equal((await request('/api/moments/delete',{album:second,id:target},viewer.cookie)).status,403);
  assert.equal(readdirSync(join(data,'uploads')).length,2);
  assert.equal((await request('/api/moments/delete',payload,cookie)).status,200);
  assert.deepEqual((await request('/api/moments?album='+album,undefined,cookie)).body.map(m=>m.id),[retained]);
  assert.equal((await request('/api/files/'+file,undefined,cookie)).status,404);
  assert.equal(readdirSync(join(data,'uploads')).length,1);
  const db=new DatabaseSync(join(data,'album.sqlite'));
  try {assert.equal(db.prepare('SELECT count(*) AS n FROM comments WHERE moment_id=?').get(target).n,0);} finally {db.close();}
  const milestone=(await request('/api/checklist?album='+album,undefined,cookie)).body.find(i=>i.key==='smile');
  assert.equal(milestone.completed,true);assert.equal(milestone.momentId,null);
  assert.equal((await request('/api/moments/delete',payload,cookie)).status,404);
  assert.equal((await create('Replacement',{milestoneKey:'smile',files:[]})).status,201);
  const source=(await create('Transfer me')).body.id;
  const foreign=(await create('Another album',{album:second,files:[]})).body.id;
  const transfer={album,id:source,targetId:retained};
  assert.equal((await request('/api/moments/delete',transfer,viewer.cookie)).status,403);
  assert.equal((await request('/api/moments/delete',{...transfer,targetId:source},cookie)).status,400);
  assert.equal((await request('/api/moments/delete',{...transfer,targetId:foreign},cookie)).status,404);
  assert.equal((await request('/api/moments/delete',{...transfer,targetId:'missing'},cookie)).status,404);
  const attachment={name:'file.pdf',type:'application/pdf',data:Buffer.from('%PDF test').toString('base64')};
  const full=(await create('Full',{files:Array.from({length:10},()=>attachment)})).body.id;
  assert.equal((await request('/api/moments/delete',{...transfer,targetId:full},cookie)).status,400);
  let before=(await request('/api/moments?album='+album,undefined,cookie)).body;
  assert.ok(before.some(m=>m.id===source),'failed transfers preserve source');
  const transferredFile=before.find(m=>m.id===source).files[0].id;
  const uploadsBefore=readdirSync(join(data,'uploads')).sort();
  assert.equal((await request('/api/comments',{moment:source,body:'Source comment'},cookie)).status,201);
  assert.equal((await request('/api/comments',{moment:retained,body:'Target comment'},cookie)).status,201);
  assert.equal((await request('/api/moments/delete',transfer,cookie)).status,200);
  const after=(await request('/api/moments?album='+album,undefined,cookie)).body;
  assert.ok(!after.some(m=>m.id===source));
  const destination=after.find(m=>m.id===retained);
  assert.equal(destination.files.length,2);
  assert.ok(destination.files.some(f=>f.id===transferredFile));
  assert.deepEqual(destination.comments.map(c=>c.body),['Target comment']);
  assert.deepEqual(readdirSync(join(data,'uploads')).sort(),uploadsBefore);
  const download=await fetch(base+'/api/files/'+transferredFile,{headers:{cookie}});
  assert.equal(download.status,200);assert.equal(await download.text(),'%PDF-1.4 test');
});
